version: 2

project_name: github-authorized-keys

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: github-authorized-keys

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - systemd/*
      - install.sh
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: stevemcquaid
    name: github-authorized-keys
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
